export const images = {
  background: require('../assets/images/background.png'),
  goals: require('../assets/images/goals.png'),
  team: require('../assets/images/team.png'),
  customers: require('../assets/images/customers.png'),
  dashboard: require('../assets/images/dashboard.png'),
  discussion: require('../assets/images/discussion.png'),
  commissions: require('../assets/images/commissions.png'),
  bounses: require('../assets/images/bounses.png'),
  contest: require('../assets/images/contest.png'),
  highlights: require('../assets/images/highlights.png'),
  reports: require('../assets/images/reports.png'),
  bell: require('../assets/images/bell.png'),
  goalsLogo: require('../assets/images/goalsLogo.png'),
  menu: require('../assets/images/menu.png'),
  tabLogo: require('../assets/images/tabLogo.png'),
  user: require('../assets/images/user.png'),
  file: require('../assets/images/file.png'),
  emptyNote: require('../assets/images/emptyNote.png'),
  trash: require('../assets/images/trash.png'),
  reminder: require('../assets/images/reminder.png'),
  calender: require('../assets/images/calender.png'),
  smile: require('../assets/images/smile.png'),
  warning: require('../assets/images/warning.png'),
};
